name: ci:test
on:
  - push
  - pull_request
jobs:
  test:
    name: Continuous integration (tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: yarn ci:test
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
